import type { ApplicationDetail } from "../contracts";
import { auxiliaryStateFixture } from "./auxiliaryStateFixture";

export function applicationFixture(
  overrides: Partial<ApplicationDetail> = {},
): ApplicationDetail {
  return {
    id: "fixture-application",
    shortId: "TEST01",
    createdAtUtc: "2026-09-03T02:00:00Z",
    applicationDate: null,
    companyName: "示例公司",
    companyType: "private",
    industry: "软件",
    positionName: "开发工程师",
    positionCategory: "研发",
    workLocation: "上海",
    applicationUrl: "https://example.com/apply",
    announcementUrl: null,
    companyUrl: null,
    positionUrl: null,
    positionDescription: "虚构的岗位介绍",
    notes: "",
    folderRelativePath: "applications/fixture",
    folderNormalizationPending: false,
    currentStageId: "stage-preparing",
    currentStageName: "准备投递",
    currentStageState: "pending",
    currentStateName: "尚未开始",
    currentStateKind: "pending",
    auxiliaryStates: auxiliaryStateFixture(overrides.id),
    currentStageOrder: 10,
    currentStageProgress: 0,
    currentStageColor: "#64748b",
    statusUpdatedAtUtc: "2026-09-03T02:00:00Z",
    updatedAtUtc: "2026-09-03T02:00:00Z",
    archivedAtUtc: null,
    deletedAtUtc: null,
    revision: 1,
    tags: [],
    documentCount: 0,
    documentNames: [],
    customFields: {},
    history: [],
    interviewRounds: [],
    documents: [],
    stages: [
      {
        id: "stage-preparing",
        stableKey: "preparing",
        displayName: "准备投递",
        stageKind: "application",
        displayOrder: 10,
        color: "#64748b",
        isTerminal: false,
        terminalOutcome: null,
      },
    ],
    ...overrides,
  };
}
